apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 2
  selector:
    matchlabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: kusumab/app1:1.0.0
          ports: 
          - containerPort: 80
---
kind: Service
apiversion: v1
metadata:
  name: nginx
spec:
  selector:
      app: app1
  ports:
   - protocols: TCP
     port: 80
     targetPort: 80


