apiVersion: apps/1
kind: Deployment
metadata:
  name: app1
  labels:
    name: app1
spec:
  replicas: 2
  selector:
    matchlabels:
      name: app1
  template:
    metadata:
      name: app1
  spec:
    containers:
      - name: app1
        image: kusumab/app1:1.0.0
        ports: 
          -containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
      name: app1
  ports:
   - protocols: TCP
     port: 80
     targetPort: 80


